--MOSTRA TABELA
SELECT*FROM CLIENTE
SELECT*FROM PEDIDO
SELECT*FROM SOLICITACAO
SELECT*FROM PRODUTO
SELECT*FROM COTACAO
SELECT*FROM NOTA


-- 2 INSERINDO DADOS NA TABELA
insert into cliente values('Eduardo','20221201','Curitiba')
insert into pedido values('20221201',800,1)
insert into solicitacao values('20221201',2)
insert into produto values('TECLADO',200)
insert into cotacao values(1,1)

--3 RELACIONAMNETO 

--CLIENTE.ID=NOTA.FK_CLIENTE_ID
--PEDIDO.ID=NOTA.FK_PEDIDO_ID
--SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
--SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
--PRODUTO.ID=COTACAO.FK_PRODUTO_ID

SELECT*FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID

INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I

INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID

INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID

INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID


-- 4 INCLUSÃO DE NOVOS CAMPOS 

ALTER TABLE PRODUTO ADD QTDE INT, EMAIL VARCHAR(60)
ALTER TABLE CLIENTE ADD BAIRROS VARCHAR(60), EMAIL VARCHAR(60)
ALTER TABLE SOLICITACAO ADD QTDE INT, TOTAL NUMERIC(12,2)
ALTER TABLE PEDIDO ADD QTDE INT, TOTAL NUMERIC(12,2)
ALTER TABLE COTACAO ADD QTDE INT, VALORUNIT NUMERIC(12,2)
ALTER TABLE NOTA ADD QTDE INT, VALORUNIT NUMERIC(12,2)

--5 ATT DE CAMPOS DAS TABELAS

UPDATE PRODUTO
SET QTDE= LEN(P1.NOME), EMAIL= TRIM(C.nome)+'@unicesumar.edu.br'

FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID


update cliente
set bairro='centro', email= TRIM(P1.nome)+'@TERRA.COM.BR'

FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID

UPDATE SOLICITACAO
SET QTDE= LEN(C.NOME), TOTAL= (S.QTDE * S.VALORUNIT)

FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID

UPDATE PEDIDO

SET QTDE= LEN(C.EMAIL), TOTAL= (P1.QTDE *P1.VALORUNITI

FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID



UPDATE COTACAO

SET QTDE= LEN(P1.EMAIL), VALORUNIT= S.VALORUNIT + DATE(GETDADE()),
TOTAL= (C.QTDE*C.VALORUNIT)

FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID


UPDATE NOTA

SET QTDE= P1.QTD+MONTH(GETDATE()), VALORUNIT= N.QTDE+YEAR(GETDATE())
TOTAL= N.QTDE*N.VALORUNIT

FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID


-- 6 LISTAR COISAS



WHERE YEAR(C.DATA=2022)
AND MONTH(S.DATA)IN (2,4,6,9)

-- 7 MOSTRAR COISAS

WHERE N.VALORTOTAL < 1000
AND N.VALORTOTAL >= 50
AND P.ID % 2=0

--8 APRESENTAR COISAS

WHERE UPPER(SUBSTRING(C.NOME,1,1)) + LOWER(SUBSTRING(C.NOME, 2))
AND P.DATA >'20220901'

--10

select top 1 c1.total*FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID

where c.nome =%m%
and day(c.data) %2=0



11-- att dados

update nota

set valoruniti= valorunit * 1.10

FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID

where s.valoruniti > 100
and c.data < '20221115'


--12att dados

update cotacao
set valoruniti= (n.qtde+s+qtde)

where LEN(p1.nome) > 10
and len(p1.nome) <40]


--13 listar quantidade 

SELECET COUNT(*)FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID

WHERE P.ID % <> 0
AND P.VALORUNIT <> 50


--15 EXCLUIR

DELETE FROM PRODUTOS

FROM CLIENTE
INNER JOIN NOTA
ON CLIENTE.ID=NOTA.FK_CLIENTE_ID
INNER JOIN PEDIDO
ON PEDIDO.ID=NOTA.FK_PEDIDO_I
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=PEDIDO.FK_SOLICITACAO_ID
INNER JOIN SOLICITACAO
ON SOLICITACAO.ID=COTACAO.FK_SOLICITACAO_ID
INNER JOIN PRODUTO
ON PRODUTO.ID=COTACAO.FK_PRODUTO_ID

WHERE C.VALORTOTAL <> N.VALORTOAL









--relacionameto

s.id=c.fk_solicitacao_id
p.id=c.fk_pedido_id
n.id=p.fk_nota_id

select*from solicitacao
inner join solicitacao
on s.id=c.fk_solicitacao_id

inner join pedido
on p.id=c.fk_pedido_id

inner join nota 
on n.id= p.fk_nota_id

alter table solicitacao add data varchar(60)

update pedido
set qtde= qtde* 1.10

update produto

set qtde= LEN(p1.nome), email= TRIM(c.nome)+'@UNICESUMAR.EDU.BR'

UPDATE CLIENTE 

SET BAIRRO= 'CENTRO', EMAIL= TRIM(P1.NOME)+'@TERRA.COM.BR'

UPDATE SOLICITACAO

SET QTDE= LEN(C.NOME), TOTAL= S.QTDE *S.VALORUNITARIO


UPDATE PEDIDO

SET QTDE= LEN(C.EMAIL), TOTAL= P.QTDE*P.VALORUNITI


UPDATE COTACAO

SET QTDE= LEN(P1.EMAIL), VALORUNIT= S.VALORUNIT+DAY(GETDATE())
TOTAL= C.QTDE*C.VALORUNITI


UPDATE NOTA

SET QTDE= P1.QTDE+MONTH(GETDATE()), VALORUNIT= N.QTDE+YEAR(GETDATE())
TOTAL= N.QTDE*N.VALORUNIT



















 
